name: Security SCA scan

on:
  pull_request:
    branches:
      - main
      - develop
      - preprod

jobs:
  trivy: 
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
      security-events: write
      actions: read
    
    steps:
      - name: 🧪 List files 1
        run: ls -la

      - name: 📥 Checkout du code
        uses: actions/checkout@v4

      - name: 🧪 List files 2
        run: ls -la

      - name: 📦 Install trivy
        run: |
          sudo apt-get install wget gnupg && \
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null&& \
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list && \
          sudo apt-get update && \
          sudo apt-get install trivy
      
      - name: 🆔 Generate unique and random string for unique file naming
        run: echo "UNIQ_STR=$(head /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 30)" >> "$GITHUB_ENV"

      - name: Run trivy for scan high vulnerabilities levels and add severity result in report
        run: |
          trivy fs --scanners vuln,secret,config . --format sarif --output output-${UNIQ_STR}.json
      
      - name: 🔄 Count and store vuln
        run: |
          jq '.runs[0].results | length' output-${UNIQ_STR}.json > vuln_count.txt
          VULN_COUNT=$(cat ./vuln_count.txt)
          echo "Nombre de vulnérabilités détectées : $VULN_COUNT"
          echo "VULN_COUNT=$VULN_COUNT" >> $GITHUB_ENV

      - name: ✅ Vérification du résultat de l’analyse
        run: |
          if [ "${VULN_COUNT}" -gt 0 ]; then
            echo "❌ ${VULN_COUNT} vulnérabilités détectées. CI bloquée."
            exit 1
          else
            echo "✅ Aucune vulnérabilité détectée. CI validée."
          fi
